### ISSUE TITLE
Inline comments to ignore violations

### ISSUE THREAD

**Issue by RojerGS** [guilatrova/tryceratops#15]
The `tryceratops` roadmap [contains a card](https://github.com/guilatrova/tryceratops/projects/1#card-64734179) that talks about replacing the inline comments `# notc` to `# notry`.

Upon further investigation, to see what other linters/related tools do, I suggest we change the inline comment to `# noqa` to prevent all linting and to `# noqa: TCxxx` to disable a specific check (or several checks, with a comma-separated list.

This stems from the fact that `flake8` (for which `tryceratops` is a plugin) uses `# noqa` to ignore the line, or `# noqa: ?xxx` to ignore specific violations (see [docs](https://flake8.pycqa.org/en/latest/user/violations.html#in-line-ignoring-errors)), where `?` is a letter to specify the class of violations and the `xxx` is the number of the violation.
This would unify the interface and allow users to use a consistent "syntax" to skip lines/violations.

If the discussion in this issue seems favourable, I'll draft a PR implementing this change.

For reference, `pylint` uses a [verbose commenting syntax](http://pylint.pycqa.org/en/latest/user_guide/message-control.html) and `black` uses `# nofmt` to ignore a specific line.

(What seems to be common across all these tools is that they allow some type of "block" disable, allowing to skip linting/checking of a block of lines.
Might be interesting to think about whether that would make sense for `tryceratops` or not.)

**Comment by guilatrova** [comment]
> If the discussion in this issue seems favourable, I'll draft a PR implementing this change.

Amazing investigation @RojerGS ! I'm on board with your proposal!

> (What seems to be common across all these tools is that they allow some type of "block" disable, allowing to skip linting/checking of a block of lines.
Might be interesting to think about whether that would make sense for tryceratops or not.)

Today, we only allow ignoring violations [per line](https://github.com/guilatrova/tryceratops/blob/main/src/tryceratops/filters.py#L23-L30) or [the whole file](https://github.com/guilatrova/tryceratops/blob/main/src/tryceratops/filters.py#L20).

It makes sense to me for `black` since it stops formatting for a few lines and then enables again for the remaining lines (I've already used it myself when defining some dicts), but I can't see the same use case for tryceratops.

We can move on using `# noqa`, and we can keep discussing the "block disable" in parallel to make a final decision.

**Comment by guilatrova** [comment]
BTW I archived the original card and added this issue to the roadmap. I appreciate a lot your effort and support! ❤️ 

If you decide to take on this, consider using the convention for [breaking change](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer) in the commit, since anyone using `notry` syntax will just stop working.
