### ISSUE TITLE
New violation: Prefer TypeError for unexpected types 

### ISSUE THREAD

**Issue by sbrugman** [guilatrova/tryceratops#32]
Hi there,

A couple of times on existing code bases I've ran into a problem with built-in exceptions. I'm hoping to interest you into accepting it into this project, as it's the closest I've seen so far to the use case.

A simple GitHub search results in many codebases struggling with this pattern.

## The issue

Often built-in exceptions are used regardless of their semantics. This results in confusing diagnostic information for the user. 

```python
if isinstance(my_var, int):
    pass
else:
    raise ValueError("...") #should be typeerror
```

The above examples has variations with multiple elif statements and other exception types as RuntimeError. 

Similarly, if the if/elif conditions check values, not type, then a TypeError is misleading.

## Proposed solution

Detect these patterns and report them, ideally fix them automatically (as pyupgrade would do). 

Are you open to including this functionality in the package? If you're to busy, but open, then the community could take a turn ([hacktoberfest](https://hacktoberfest.digitalocean.com/)).

**Comment by guilatrova** [comment]
Hi @sbrugman ! 👋
Thanks for trying Tryceratops 🦖  and sharing your thoughts.

### Violation definition

That's a great suggestion! The [Python docs](https://docs.python.org/3/library/exceptions.html#TypeError) makes the definition clear:

> Raised when an operation or function is applied to an object of inappropriate type. [...]
> This exception may be raised by user code to indicate that an attempted operation on an object is not supported [...]
> Passing arguments of the wrong type (e.g. passing a list when an int is expected) should result in a TypeError, but passing arguments with the wrong value (e.g. a number outside expected boundaries) should result in a ValueError.

So it fits the description you just mentioned!  I'd suggest we create a new Violation: **TC004 - Prefer `TypeError` exception for invalid type**.

### Autofix support

I agree, we already have some implemented, so it should be fine.

### Variant support

I believe we should stick just to some classic built-in exception classes... But I'm not completely sure yet.
I'd recommend considering only the following classes:  `Exception`, `ValueError`, and `RuntimeError` as you mentioned. Do you feel strongly about including any other types?

I just want to ensure the developer can create a `class OperationXUnsupportedType(TypeError)` if he wishes.

### Implementation + Release

> Are you open to including this functionality in the package? 

Yes! 😄 

> If you're too busy, but open, then the community could take a turn (hacktoberfest).

I'm kind of busy due to my work and other side projects regarding microservices that I'm planning to do 😢 
so I can't commit to delivering it. I'll check how to include Tryceratops into the hacktoberfest! Thanks for suggesting!

Also, be my guest to implement it if you have the time! ❤️ 😄

**Comment by swellander** [comment]
Hi there @guilatrova - mind if I take a crack at an implementation?

**Comment by guilatrova** [comment]
@swellander Be my guest! Thanks for suggesting ❤️

Please, check out the [contributing guidelines](https://github.com/guilatrova/tryceratops/blob/259bf9c1eb357f2ebf737f5b3f9c52220645490f/docs/CONTRIBUTING.md), and take some time to understand how the commit messages play with the auto release setup.

**Comment by swellander** [comment]
@guilatrova sounds good, will do!
